# Generated by Django 4.1.5 on 2023-01-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listingcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingComment',
            new_name='Comment',
        ),
    ]
