# Generated by Django 4.1.5 on 2023-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auctionlisting_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='listing_status',
            field=models.BooleanField(default=True),
        ),
    ]
