# Generated by Django 4.1.5 on 2023-02-08 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_bid_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='time',
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
